### ISSUE TITLE
Factory.getVersion() etc not accurate

### ISSUE THREAD

**Issue by paulswithers** [OpenNTF/org.openntf.domino#125]
Factory.getVersion() returns "2.6 (04-16-2014)". I checked Factory.getTitle() which also goes to the manifest, and that returns "Java Runtime API". Looks like it's getting the wrong Manifest.MF - perhaps something to do with loadEnvironment using "if (!jar_init)"??

**Comment by jesse-gallagher** [comment]
This works better now (it at least uses the right manifest), but the mechanism is dodgy and the title refers to a manifest header we don't use.
