### ISSUE TITLE
DocumentCollection.isEmpty() is wrong

### ISSUE THREAD

**Issue by MarkusLanger** [OpenNTF/org.openntf.domino#132]
public boolean isEmpty() {  
    return this.size() > 0;
}

Is checking is this.size() > 0, so actually returning whether it's NOT empty.

**Comment by spanky762** [comment]
I have verified this in my own testing.
Created a DocumentCollection with 1 document. 
collection.getCount() returns 1
collection.isEmpty() returns true
collection.getFirstDocument() returns a valid document.
