### ISSUE TITLE
Possible problem with ViewEntry.columnValues()

### ISSUE THREAD

**Issue by leedy** [OpenNTF/org.openntf.domino#138]
I made a flat view.  3 columns - barcode, date, jobCode

Inside my personal "Item" object, which represents a physical object and NOT a NotesItem,  I have a method to populate the last used date from this view.

When using the ViewEntry Object, and my entry was created from this line:
ViewEntry entry = vHistory.getFirstEntryByKey(this.getBarCodeHuman(), true);

A later test proved entry.getColumnValues() was null.
This line printed on the console:
if (null == doc.getColumnValues()) { throw new NullPointerException("ColumnValues is null"); }

The maddening thing here is sometimes the code did seem to run fine.  Other times it would not.  When it did break it would do so on different documents.  So it usually hit early in this process but always on a different "Widget".  

What I'm doing is generating an XPage report.  I'm populating a big table.  So I'm looping through about 2,000 "Items" to run this code.  I've changed the code to use the slower getDocumentByKey() and that's run fine now 6 times in a row.

Screenshot of the Stack Trace

![image](https://cloud.githubusercontent.com/assets/1387400/10667716/bff30f46-78a6-11e5-98c8-0a1c8dbff126.png)

An Earlier screenshot from the console before I put more debug statements in : 
![image](https://cloud.githubusercontent.com/assets/1387400/10667741/e0ac6bec-78a6-11e5-8ca3-a54d3b317f2d.png)

Below is the source code of my method AFTER I converted to getDocumentByKey but you can see what it looked like when using ViewEntries.  

private void findLastShow() {
        this.console("Looking for LAST Job and SHOW for Item : " + this.getBarCodeHuman());

```
    // If this isn't a valid item then nothing to do.
    if (!this.valid) {
        this.console("Job is Not Valid");
        lastShow = "";
        lastJobDesc = "";
        lastJobCode = "";
        lastShowDate = null;
        return;
    }

    Session session = this.getSession();

    Database currentDB = session.getCurrentDatabase();
    Database histDB = session.getDatabase(currentDB.getServer(),"czTraq\\histinfo.nsf");
    View vHistory = histDB.getView("lkup_lastJob");
    vHistory.setAutoUpdate(false);

    // This view only has history documents that include a job number
    //  It's sorted date descending so the First Entry should give me the last job this item was at

    // ViewEntry entry = vHistory.getFirstEntryByKey(this.getBarCodeHuman(), true);
    Document lookupDoc = vHistory.getFirstDocumentByKey(this.getBarCodeHuman(), true);

    if (lookupDoc == null) {
        // no history document found.
        this.console("No History Document Found");
        lastShow = "";
        lastJobDesc = "";
        lastJobCode = "";
        lastShowDate = null;
    } else {


    //  if (null == lookupDoc) { throw new NullPointerException("doc is null"); }
    //  if (null == doc.getColumnValues()) { throw new NullPointerException("ColumnValues is null"); }





        String tmpCode = lookupDoc.getItemValueString("jobCode");
        this.console("tmpCode : " + tmpCode);



        Job job = new Job();
        job.load(tmpCode);
        this.console("JOB VALID : " + job.isValid());
        this.console("JOB DELETED : " + job.getIsDeleted());


        if (job.getIsDeleted()) {
            this.console("Job has been Deleted");
            // This job has been deleted.  Little to no information available.  Ignore
            lastShow = "";
            lastJobDesc = "";
            lastJobCode = "";
            lastShowDate = null;    
        } else {
            // We have a proper job.
            this.console("We have a Good Job");
            this.lastJobCode = tmpCode;
            this.lastJobDesc = job.getJobDesc();
            this.lastShowDate = job.getEndDate();

            // Get the Show Info
            CzarShow show = job.getShow();
            if ((null == show) || (!show.getIsValid())) {
                // show is either null or not valid.
                this.lastShow = "";
            } else {
                // We should have a good show.
                this.lastShow = show.getName();
            }

        }
    }
    this.console("End of Method");
    vHistory.setAutoUpdate(true);

}
```

**Comment by leedy** [comment]
Here's the stack trace from the server.  I couldn't add the txt file so it's a screenshot.


![image](https://cloud.githubusercontent.com/assets/1387400/10670872/ade74394-78b5-11e5-86b0-8ee90c803965.png)

**Comment by paulswithers** [comment]
You mentioned that it was logging out on a line that checked whether the ViewEntry is null. Can you also check whether any of the objects higher up the hierarchy are also null - view, database etc? The ViewEntry may have been recycled because of an ancestor being recycled. It may also be worth double-checking what key it was looking up on, to double-check whether the ViewEntry is being recycled or whether the earlier check for null is incorrect (I doubt the latter, but good to confirm).
