### ISSUE TITLE
Domino API in XPINC

### ISSUE THREAD

**Issue by windgaucho** [OpenNTF/org.openntf.domino#139]
I am trying to use the domino api (and the last version of extension library too) in a XPINC application, and when I try to run and test the application in one of my clients I get an error that the application is not able to load the library.
I my developer pc all works as expected but in the client pc does not work. I read the chapter in the extension library book in wich details how to make a widget in order to install the library in the clients, but all the procedures detailed in the book did not work.
It is a way on how can install the libraries in the clients? can I make a manual copy of these libraries?

Thanks.

**Comment by jesse-gallagher** [comment]
Hrm, diagnosing problems with policies are always tricky, but I can say that the policy+widgets route has indeed worked for me in the past, as described here: https://www-01.ibm.com/support/knowledgecenter/#!/SSKTMJ_9.0.1/admin/inst_deployingclientpluginswithwidgetsandthewidgetcat_c.dita <https://www-01.ibm.com/support/knowledgecenter/#!/SSKTMJ_9.0.1/admin/inst_deployingclientpluginswithwidgetsandthewidgetcat_c.dita> . I suspect that the trouble you’re having is somewhere in that setup.

**Comment by paulswithers** [comment]
Also, on the relevant PC, check Help > Support > View Log and Help > Support > View Trace. The Notes Client itself writes a lot of information there, so there is likely to be quite a number of log entries, even if Notes has only recently been started. If there are any ODA-related messages logged there, can you please add them to the issue - they may help identify where the problem lies.

**Comment by windgaucho** [comment]
Hello again, thanks you bouth for your responses and sorry for the delay in my response. The installation plugin is woriking now, but I have to wait to the my admin it sector for recreate the policy and the widget and try again from the scratch follow de advice of mr. Gallagher.

We recreate the widget and the policy but nothing happens. In the lotus client progress bar onldy show "Widget Provisioning" but nothing else happens. In the Help -> Support -> View Trace, there was nothing realted with ODA or Extension Library.
So, in the end we check the client configuration (in the Online Location, Online -> Edit Locations -> Online) and found that in the Server Section was missing the name of the domain server in some of the textbox available there. We complete the textobox with the name of our server, restart the cliente and the plugin work as expected. The library is installed and work in the client.

Thanks you very much for your support!!
