### ISSUE TITLE
Session as signer

### ISSUE THREAD

**Issue by leader80** [OpenNTF/org.openntf.domino#143]
Hi,

is there any way to get the session as a signer with the optntf API?

Session signerSession = ExtLibUtil.getCurrentSessionAsSigner();

cheers
G

**Comment by paulswithers** [comment]
That will work in XPages if you have godmode set as one of the switches. Alternatively ExtLibUtil.resolveVariable("sessionAsSigner") or, without the switch, ExtLibUtil.resolveVariable("openSessionAsSigner")

**Comment by paulswithers** [comment]
There's also an ODA chat on OpenNTF's Slack channel. Just register to the OpenNTF Slack from http://openntf.org and it's a channel you can add

**Comment by leader80** [comment]
I was thinking about the session class, there is no factory for that.
I know I can read and use the extension lib to gather it.

How would you cast a lotus.domino.Session into an org.openntf.domino.Session?
thanks for your reply
G.
