### ISSUE TITLE
Improved performance of ViewNavigatorEntryIterator

### ISSUE THREAD

**Issue by 4ndyc** [OpenNTF/org.openntf.domino#161]
Performance of the `ViewNavigatorEntryIterator` can be boosted by around 20% - 30% compared to the existing implementation by altering it to use `ViewNavigator.getNext()` rather than `ViewNavigator.getNext(ViewEntry)` - see [http://linqed.eu/2017/05/12/convenience-at-a-cost-comparing-domino-java-apis-performance-oda-legacy-jna/](url). I've tested the following implementation, comments etc excluded for brevity:

```
public class ViewNavigatorEntryIterator implements Iterator<ViewEntry> {

	private transient ViewNavigator navigator_;
	private transient ViewEntry currentEntry_;
	private transient ViewEntry nextEntry_;
	
	public ViewNavigatorEntryIterator(ViewNavigator navigator) {
		navigator_ = navigator;
		nextEntry_ = navigator_.getFirst();
	}
	
	public boolean hasNext() {
		return nextEntry_ != null;
	}
	
	public ViewEntry next() {
		if (hasNext()) {
			currentEntry_ = nextEntry_;
			nextEntry_ = navigator_.getNext();
			return currentEntry_;
		} else {
			return null;
		}
	}

	public void remove() {
		// Not implemented
	}
	
}
```

**Comment by the-ntf** [comment]
Wow that's great insight. I will check this in tonight!

**Comment by 4ndyc** [comment]
Although the results still stand, on further investigation `ViewNavigator.getNext(ViewEntry)` doesn't look like the culprit. The actual cause of the problem is the call to `hasNext` in the iterator's `next` method, which  increases the number of API calls.
