### ISSUE TITLE
Deploy to Maven Central

### ISSUE THREAD

**Issue by mattcg** [OpenNTF/org.openntf.domino#163]
In order to facilitate use of this library in a file parsing/forensics framework like Apache Tika, would it be possible to deploy the `domino` module to Maven Central?

**Comment by paulswithers** [comment]
We have it deployed to OpenNTF Artifactory. Just add this to your pom.xml

`	<repositories>
		<repository>
			<id>org.openntf.domino</id>
			<url>https://artifactory.openntf.org/openntf/</url>
		</repository>
	</repositories>`

Then

`		<dependency>
			<groupId>org.openntf.domino</groupId>
			<artifactId>org.openntf.domino</artifactId>
			<version>${oda-version}</version>
		</dependency>`

I usually keep my version number in a variable, it seems to be standard from what I've seen of other poms. So in properties I have `<oda-version>4.0.0-SNAPSHOT</oda-version>`.

Unfortunately to build automatically via Bamboo and deploy to Artifactory, it needs to Domino Update Site for Build Management project of the relevant release version. We're still waiting for official versions of FP8 and FP9, so 4.0.0-SNAPSHOT is the latest, which covers up to and including 9.0.1 FP7. I've raised the issue with IBM, hopefully we can get a version soon. I'll keep this updated.

**Comment by mattcg** [comment]
Thank you, this works for now!
