### ISSUE TITLE
doc.hasItem("fieldName") call causes multiple session Evaluate calls

### ISSUE THREAD

**Issue by PatrickKwinten** [OpenNTF/org.openntf.domino#185]
- [12.0.1 FP1 ] Domino server version (relevant for runtime issues)
- [12.0.1 FP1] Domino Designer version (relevant for compile-time issues)
- [11.0.1 ] ODA version
- [x] Steps to reproduce
- [x] Expected behaviour
- [ ] Actual behaviour

I notice 1 doc.hasItem("fieldName") call causes multiple (4) session Evaluate calls according to xpages toolbox

Code to reproduce:

import java.io.Serializable;
import java.util.Vector;

import org.openntf.domino.View;
import org.openntf.domino.utils.Factory;
import org.openntf.domino.utils.Factory.SessionType;
import org.openntf.domino.Database;
import org.openntf.domino.Document;

import org.openntf.domino.Session;
import com.ibm.xsp.extlib.util.ExtLibUtil;

public class TestBean implements Serializable{

	public TestBean(){
		System.out.println("constructor TestBean");
	}
	
	public void test(){
		System.out.println("test()");
		try{
			Session session = Factory.getSession(SessionType.CURRENT);
			
			Database db = session.getCurrentDatabase();
			View vw = db.getView("luProfile");
			Document doc = vw.getFirstDocument();
			if(doc.hasItem("DbPath")){
				String DbPath = doc.getItemValueString("DbPath");
			}
		} catch(Exception e){
			System.out.println(e.toString());
		}
	}
}

**Comment by perlausten** [comment]
This was fixed by @jesse-gallagher on Feb 11, 2022 in this commit: https://github.com/OpenNTF/org.openntf.domino/commit/53fbb443327b581e8177e03e26bcd43dd286eae5
