### ISSUE TITLE
Factory.getSession() returns null after first successul run

### ISSUE THREAD

**Issue by nheidloff** [OpenNTF/org.openntf.domino#58]
When I call the same method from my XPage a second time (e.g. click button twice) then Factory.getSession returns null. I then have to restart my server as workaround.

![image](https://f.cloud.github.com/assets/1425685/673238/d58984dc-d8af-11e2-8f7c-673cdaf80118.png)

![image](https://f.cloud.github.com/assets/1425685/673240/dd96ad4e-d8af-11e2-98a0-f25213638fa1.png)

**Comment by jesse-gallagher** [comment]
The code has changed quite a bit since this time, and I have XSP-side tests that do similarly without issue, so it's fair to assume that this is fixed.
